-- SCHEMA: schm_prj_test2
-- DROP SCHEMA IF EXISTS schm_prj_test2;
CREATE SCHEMA IF NOT EXISTS schm_prj_test2
    AUTHORIZATION chicago;
COMMENT ON SCHEMA schm_prj_test2
    IS 'Projeto da #localizacao#, gerido por #gestor#';

/* PERMITS ROLES
-- Read-only role (RECEBE O PROJETO)
CREATE ROLE readonly;
-- #PERMIT
GRANT prj_group_role TO readonly
-- GRANT CONNECT ON DATABASE byon TO readonly;
-- GRANT USAGE ON SCHEMA prj_schema TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA prj_schema TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA prj_schema GRANT SELECT ON TABLES TO readonly;

-- Read/write role
CREATE ROLE readwrite;
-- #PERMIT
GRANT prj_group_role TO readwrite
--GRANT CONNECT ON DATABASE byon TO readwrite;
GRANT USAGE, CREATE ON SCHEMA prj_schema TO readwrite;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA prj_schema TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA prj_schema GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA prj_schema TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA prj_schema GRANT USAGE ON SEQUENCES TO readwrite;
*/

-- GROUP ROLE (cannot login): prj_group_role
CREATE ROLE prj_group_role WITH
	NOLOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1;
-- PERMITS
GRANT CONNECT ON DATABASE byon TO prj_group_role;
-- INITIAL USAGE
GRANT USAGE ON SCHEMA schm_prj_test2 TO prj_group_role;
GRANT SELECT ON ALL TABLES IN SCHEMA schm_prj_test2 TO prj_group_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA schm_prj_test2 GRANT SELECT ON TABLES TO prj_group_role;


-- CREATE USERS (R|RW) (can login)
CREATE ROLE r_pessoa WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '123';
-- PERMITS
GRANT prj_group_role TO r_pessoa 
-- GRANT SELECT ON ALL TABLES IN SCHEMA schm_prj_test2 TO r_pessoa 
-- ALTER DEFAULT PRIVILEGES IN SCHEMA schm_prj_test2 GRANT SELECT ON TABLES TO r_pessoa 

CREATE ROLE rw_pessoa WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '123';
-- PERMITS
GRANT prj_group_role TO rw_pessoa;
GRANT USAGE, CREATE ON SCHEMA prj_schema TO rw_pessoa

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA schm_prj_test2 TO rw_pessoa;
ALTER DEFAULT PRIVILEGES IN SCHEMA schm_prj_test2 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw_pessoa;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA schm_prj_test2 TO rw_pessoa;
ALTER DEFAULT PRIVILEGES IN SCHEMA schm_prj_test2 GRANT USAGE ON SEQUENCES TO rw_pessoa;

/*RESET
DROP SCHEMA IF EXISTS schm_prj_test2;
-- REMOVE GROUP-ROLES
REVOKE ALL PRIVILEGES ON DATABASE byon FROM r_pessoa;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM r_pessoa;
REASSIGN OWNED BY r_pessoa TO chicago;
DROP ROLE r_pessoa;

REVOKE ALL PRIVILEGES ON DATABASE byon FROM rw_pessoa;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM rw_pessoa;
REASSIGN OWNED BY rw_pessoa TO chicago;
DROP ROLE rw_pessoa;

REVOKE ALL PRIVILEGES ON DATABASE byon FROM prj_group_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM prj_group_role;
REASSIGN OWNED BY prj_group_role TO chicago;
DROP ROLE prj_group_role;
*/