from django.db import models
from datetime import datetime

class Plugin(models.Model):
    name = models.CharField(max_length=100)
    qgis_minimum_version = models.CharField(max_length=10)
    qgis_maximum_version = models.CharField(max_length=10, default='3.98')
    description = models.TextField()
    version = models.CharField(max_length=10)
    author = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    about = models.TextField()
    tracker = models.URLField()
    repository = models.URLField()
    tags = models.CharField(max_length=200)
    homepage = models.URLField()
    category = models.CharField(max_length=100)
    icon = models.URLField(default='')
    experimental = models.BooleanField(default=False)
    deprecated = models.BooleanField(default=False)
    server = models.BooleanField(default=False)
    has_processing_provider = models.BooleanField(default=False)
    changelog = models.TextField(blank=True)
    plugin_dependencies = models.CharField(max_length=200, blank=True, default='')
    file_name = models.CharField(max_length=100)
    download_url = models.URLField()
    uploaded_by = models.CharField(max_length=100)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    external_dependencies = models.CharField(max_length=200, blank=True, default='')
    downloads = models.IntegerField(default=0)
