# Generated by Django 5.0.2 on 2024-03-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_user_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='application',
        ),
    ]
