# Generated by Django 5.0.3 on 2024-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qgis_minimum_version', models.CharField(max_length=10)),
                ('qgis_maximum_version', models.CharField(default='3.98', max_length=10)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about', models.TextField()),
                ('tracker', models.URLField()),
                ('repository', models.URLField()),
                ('tags', models.CharField(max_length=200)),
                ('homepage', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('icon', models.URLField(default='')),
                ('experimental', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('server', models.BooleanField(default=False)),
                ('has_processing_provider', models.BooleanField(default=False)),
                ('changelog', models.TextField(blank=True)),
                ('plugin_dependencies', models.CharField(blank=True, default='', max_length=200)),
                ('file_name', models.CharField(max_length=100)),
                ('download_url', models.URLField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('external_dependencies', models.CharField(blank=True, default='', max_length=200)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
    ]
