# Generated by Django 5.0.2 on 2024-03-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
        ('warehouse', '0002_delete_event_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shed',
            name='shed',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
