# Generated by Django 5.0.2 on 2024-03-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_outboundrequest_task_alter_rack_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('outbound_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.outboundrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item')),
            ],
        ),
        migrations.AddField(
            model_name='outboundrequest',
            name='products',
            field=models.ManyToManyField(through='warehouse.OutboundProduct', to='warehouse.item'),
        ),
    ]
